import { Monoton, Neucha, Emblema_One } from "next/font/google";
import "./globals.css";

export const monoton = Monoton({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-monoton",
});

const neucha = Neucha({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-neucha",
});

const emblema = Emblema_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-emblema",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${monoton.variable} ${neucha.variable} ${emblema.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
